#import <Foundation/Foundation.h>
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AKAppleIDAuthenticationContext.h"

#import "AKAppleIDAuthenticationUIProvider-Protocol.h"

@class AKNativeAccountRecoveryController, NSImage, NSString, NSView, NSWindow;
@protocol AKAppleIDAuthenticationInAppContextAlertDelegate, AKAppleIDAuthenticationInAppContextPasswordDelegate, CDPStateUIProvider;

@interface AKAppleIDAuthenticationInAppContext : AKAppleIDAuthenticationContext <AKAppleIDAuthenticationUIProvider>
{
    AKNativeAccountRecoveryController *_nativeRecoveryController;
    BOOL _makeSheetCritical;
    BOOL _showRememberPasswordCheckbox;
    BOOL _rememberPassswordCheckedByDefault;
    BOOL _hideAlternativeButton;
    BOOL _hideCancelButton;
    BOOL _clientShouldHandleAlternativeButtonAction;
    BOOL _shouldPreventSignIn;
    BOOL _hideReasonString;
    BOOL _alwaysShowUsernameField;
    NSString *_cancelButtonString;
    NSString *_privacyBundleIdentifier;
    NSWindow *_hostWindow;
    NSView *_hostView;
    NSString *_rememberPasswordCheckboxString;
    NSString *_alternativeButtonString;
    long long _selectedButton;
    NSImage *_displayImage;
    NSString *_initialError;
    NSString *_windowTitle;
    id  _inAppAuthUIProvider;
     id  _alertDelegate;
     id  _cdpUiProvider;
     id  __passwordDelegate;
}


@property(nonatomic, setter=_setPasswordDelegate:) __weak  id  _passwordDelegate; // @synthesize _passwordDelegate=__passwordDelegate;
@property(retain, setter=_setCdpUiProvider:)  id  cdpUiProvider; // @synthesize cdpUiProvider=_cdpUiProvider;
@property(nonatomic) __weak  id  alertDelegate; // @synthesize alertDelegate=_alertDelegate;
@property(retain, nonatomic)  id  inAppAuthUIProvider; // @synthesize inAppAuthUIProvider=_inAppAuthUIProvider;
@property BOOL alwaysShowUsernameField; // @synthesize alwaysShowUsernameField=_alwaysShowUsernameField;
@property(retain) NSString *windowTitle; // @synthesize windowTitle=_windowTitle;
@property(retain) NSString *initialError; // @synthesize initialError=_initialError;
@property(retain) NSImage *displayImage; // @synthesize displayImage=_displayImage;
@property long long selectedButton; // @synthesize selectedButton=_selectedButton;
@property BOOL hideReasonString; // @synthesize hideReasonString=_hideReasonString;
@property BOOL shouldPreventSignIn; // @synthesize shouldPreventSignIn=_shouldPreventSignIn;
@property BOOL clientShouldHandleAlternativeButtonAction; // @synthesize clientShouldHandleAlternativeButtonAction=_clientShouldHandleAlternativeButtonAction;
@property BOOL hideCancelButton; // @synthesize hideCancelButton=_hideCancelButton;
@property BOOL hideAlternativeButton; // @synthesize hideAlternativeButton=_hideAlternativeButton;
@property(retain) NSString *alternativeButtonString; // @synthesize alternativeButtonString=_alternativeButtonString;
@property BOOL rememberPassswordCheckedByDefault; // @synthesize rememberPassswordCheckedByDefault=_rememberPassswordCheckedByDefault;
@property(retain) NSString *rememberPasswordCheckboxString; // @synthesize rememberPasswordCheckboxString=_rememberPasswordCheckboxString;
@property BOOL showRememberPasswordCheckbox; // @synthesize showRememberPasswordCheckbox=_showRememberPasswordCheckbox;
@property BOOL makeSheetCritical; // @synthesize makeSheetCritical=_makeSheetCritical;
@property(retain) NSView *hostView; // @synthesize hostView=_hostView;
@property __weak NSWindow *hostWindow; // @synthesize hostWindow=_hostWindow;
@property(copy) NSString *privacyBundleIdentifier; // @synthesize privacyBundleIdentifier=_privacyBundleIdentifier;
@property(retain) NSString *cancelButtonString; // @synthesize cancelButtonString=_cancelButtonString;
- (void)showCDPView:(id)arg1 modalForWindow:(id)arg2 withController:(id)arg3;
- (void)endCDPView;
- (id)init;
- (void)_contextDidEndPresentingSecondaryUI;
- (void)_contextWillBeginPresentingSecondaryUI;
- (void)dismissServerProvidedUIWithCompletion:(id)arg1;
- (void)dismissNativeRecoveryUIWithCompletion:(id)arg1;
- (void)presentNativeRecoveryUIWithContext:(id)arg1 completion:(id)arg2;
- (void)_dismissServerProvidedUIWithCompletion:(id)arg1;
- (void)presentServerProvidedUIWithConfiguration:(id)arg1 completion:(id)arg2;
- (void)presentBiometricOrPasscodeValidationForAppleID:(id)arg1 completion:(id)arg2;
- (void)dismissSecondFactorUIWithCompletion:(id)arg1;
- (void)presentSecondFactorAlertWithError:(id)arg1 title:(id)arg2 message:(id)arg3 completion:(id)arg4;
- (void)presentSecondFactorUIWithCompletion:(id)arg1;
- (void)dismissKeepUsingUIWithCompletion:(id)arg1;
- (void)presentKeepUsingUIForAppleID:(id)arg1 completion:(id)arg2;
- (void)dismissBasicLoginUIWithCompletion:(id)arg1;
- (void)presentLoginAlertWithError:(id)arg1 title:(id)arg2 message:(id)arg3 completion:(id)arg4;
- (void)presentBasicLoginUIWithCompletion:(id)arg1;
- (void)_assertValidPresentingViewController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) NSUInteger hash;
@property(readonly) Class superclass;

@end

