#import <Foundation/Foundation.h>
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AKAppleIDServerResourceLoadDelegate, AKAppleIDServerUIDataHarvester, AKServerRequestConfiguration, NSHTTPURLResponse, NSURL;

@interface AKAppleIDServerUIContextController : NSObject
{
    id _serverUICompletion;
    NSHTTPURLResponse *_latestReadResponse;
    AKServerRequestConfiguration *_configuration;
    AKAppleIDServerResourceLoadDelegate *_serverUIDelegate;
    AKAppleIDServerUIDataHarvester *_serverDataHarvester;
    NSURL *_initiatingURL;
}


@property(readonly, copy, nonatomic) NSURL *initiatingURL; // @synthesize initiatingURL=_initiatingURL;
@property(readonly, nonatomic) AKAppleIDServerUIDataHarvester *serverDataHarvester; // @synthesize serverDataHarvester=_serverDataHarvester;
@property(readonly, nonatomic) AKAppleIDServerResourceLoadDelegate *serverUIDelegate; // @synthesize serverUIDelegate=_serverUIDelegate;
- (void)_completeWithResponse:(NSHTTPURLResponse*)arg1 additionalData:(NSData*)arg2 error:(NSError*)arg3;
- (void)completeWithFinalResponse:(NSHTTPURLResponse*)arg1;
- (void)completeWithError:(NSError*)arg1 additionalData:(NSData*)arg2;
- (void)completeWithError:(NSError*)arg1;
- (void)processResponse:(NSHTTPURLResponse*)arg1;
- (id)_headerValueFromType:(unsigned long long)arg1;
- (void)signRequest:(NSMutableURLRequest*)arg1 withCompletionHandler:(id)arg2;
- (BOOL)handleAuthKitActionAttribute:(id)arg1;
- (id)initWithRequestConfiguration:(AKServerRequestConfiguration*)arg1 completion:(void (^)(NSHTTPURLResponse*, NSDictionary*, NSError*))arg2;
- (void)tearDownContext;

@end

