#import <Foundation/Foundation.h>
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSRemoteViewController, NSViewController;

@interface AKAuthorizationViewHelper : NSObject
{
    NSRemoteViewController *_remoteViewController;
}

+ (void)requestAuthorizationViewControllerWithCompletion:(id)arg1;

@property(retain) NSRemoteViewController *remoteViewController; // @synthesize remoteViewController=_remoteViewController;
- (void)setupWithRequestContext:(id)arg1 completion:(id)arg2;
- (id)serviceProxy;
@property(readonly) NSViewController *viewController;
- (void)dealloc;

@end

