#import <Foundation/Foundation.h>
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AKAuthorizationUIProvider-Protocol.h"

@class AKAuthorizationWindowController, NSString, NSWindow;

@interface AKAuthorizationUIProviderImp : NSObject <AKAuthorizationUIProvider>
{
    NSWindow *_hostWindow;
    AKAuthorizationWindowController *_authorizationWindowController;
}


@property(retain) AKAuthorizationWindowController *authorizationWindowController; // @synthesize authorizationWindowController=_authorizationWindowController;
@property __weak NSWindow *hostWindow; // @synthesize hostWindow=_hostWindow;
- (void)presentAuthorizationUIForContext:(id)arg1 completion:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) NSUInteger hash;
@property(readonly) Class superclass;

@end

