#import <Foundation/Foundation.h>
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AKAuthorizationPaneViewController.h"

@class AKAuthorizationPresentationContext;
@protocol AKAuthorizationPasswordAuthenticationDelegate;

@interface AKAuthorizationPasswordAuthenticationViewController : AKAuthorizationPaneViewController
{
     id  _delegate;
    AKAuthorizationPresentationContext *_presentationContext;
}


@property(retain, nonatomic) AKAuthorizationPresentationContext *presentationContext; // @synthesize presentationContext=_presentationContext;
@property(nonatomic) __weak  id  delegate; // @synthesize delegate=_delegate;
- (void)dealloc;
- (id)_username;
- (id)_contextForAuthentication;
- (void)presentInWindow:(id)arg1;
- (void)viewDidLoad;

@end

