#import <Foundation/Foundation.h>
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//#import <ViewBridge/NSRemoteViewController.h>

#import "AKAuthorizationViewHostDelegate-Protocol.h"

@protocol AKAuthorizationViewHostDelegate;

@interface AKAuthorizationPresenterViewController : NSObject <AKAuthorizationViewHostDelegate>
{
     id  _delegate;
}

+ (void)requestViewControllerWithCompletion:(id)arg1;

@property(nonatomic) __weak  id  delegate; // @synthesize delegate=_delegate;
- (void)callCompletionWithAuthorization:(id)arg1 error:(id)arg2;
- (id)exportedInterface;
- (id)serviceViewControllerInterface;

@end

