#import <Foundation/Foundation.h>
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol NSCopying;

@interface AKBasicLoginActions : NSObject <NSCopying>
{
    id _authenticateAction;
    id _ak_cancelAction;
    id _createIDAction;
    id _useIDAction;
    id _forgotIDAction;
    id _forgotPasswordAction;
}


@property(copy, nonatomic) id forgotPasswordAction; // @synthesize forgotPasswordAction=_forgotPasswordAction;
@property(copy, nonatomic) id forgotIDAction; // @synthesize forgotIDAction=_forgotIDAction;
@property(copy, nonatomic) id useIDAction; // @synthesize useIDAction=_useIDAction;
@property(copy, nonatomic) id createIDAction; // @synthesize createIDAction=_createIDAction;
@property(copy, nonatomic) id ak_cancelAction; // @synthesize ak_cancelAction=_ak_cancelAction;
@property(copy, nonatomic) id authenticateAction; // @synthesize authenticateAction=_authenticateAction;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

