#import <Foundation/Foundation.h>
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol NSCopying;

@interface AKBasicLoginSecondFactorActions : NSObject <NSCopying>
{
    id _regenerateCodeAction;
    id _codeEnteredAction;
    id _ak_cancelAction;
}


@property(copy, nonatomic) id ak_cancelAction; // @synthesize ak_cancelAction=_ak_cancelAction;
@property(copy, nonatomic) id codeEnteredAction; // @synthesize codeEnteredAction=_codeEnteredAction;
@property(copy, nonatomic) id regenerateCodeAction; // @synthesize regenerateCodeAction=_regenerateCodeAction;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

