#import <Foundation/Foundation.h>
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AKAppleIDAuthenticationUIProvider-Protocol.h>
#import <AKAppleIDAuthenticationInAppContext.h>
#import <AKServerRequestConfiguration.h>
#import <AppKit/AppKit.h>

@protocol NSObject;

@class AKAppleIDAuthenticationInAppContext, AKServerRequestConfiguration, NSView, NSWindow, NSError;

@protocol AKInAppAuthenticationUIProvider <NSObject, AKAppleIDAuthenticationUIProvider>
- (void)dismissCDPUI;
- (void)presentCDPView:(NSView *)arg1 withContext:(AKAppleIDAuthenticationInAppContext *)arg2 modalForWindow:(NSWindow *)arg3 withController:(id *)arg4;
- (void)presentIDPProvidedUIWithConfiguration:(AKServerRequestConfiguration *)arg1 completion:(void (^)(NSHTTPURLResponse *, NSDictionary *, NSError *))arg2;
@end

