#import <Foundation/Foundation.h>
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <AKInAppAuthenticationUIProvider-Protocol.h>

@class AKAppleIDAuthenticationInAppContext, AKAuthenticationPromptController, NSString;

@interface AKInAppAuthenticationMacOSUIProvider : NSObject <AKInAppAuthenticationUIProvider>
{
    AKAppleIDAuthenticationInAppContext *_context;
    AKAuthenticationPromptController *_authenticationPrompt;
    int _numberOfAttempts;
}


- (void)_setupButtonActionsForSignInController:(id)arg1 withCompletion:(id)arg2;
- (void)_setupAuthenticationPromptControllerAtMode:(long long)arg1;
- (void)_updateUI:(id)arg1;
- (void)dismissCDPUI;
- (void)presentCDPView:(id)arg1 withContext:(id)arg2 modalForWindow:(id)arg3 withController:(id)arg4;
- (void)dismissNativeRecoveryUIWithCompletion:(id)arg1;
- (void)presentNativeRecoveryUIWithContext:(id)arg1 completion:(id)arg2;
- (void)presentBiometricOrPasscodeValidationForAppleID:(id)arg1 completion:(id)arg2;
- (void)dismissServerProvidedUIWithCompletion:(id)arg1;
- (void)presentServerProvidedUIWithConfiguration:(id)arg1 completion:(id)arg2;
- (void)presentIDPProvidedUIWithConfiguration:(id)arg1 completion:(id)arg2;
- (void)dismissSecondFactorUIWithCompletion:(id)arg1;
- (void)presentSecondFactorAlertWithError:(id)arg1 title:(id)arg2 message:(id)arg3 completion:(id)arg4;
- (void)presentSecondFactorUIWithCompletion:(id)arg1;
- (void)dismissKeepUsingUIWithCompletion:(id)arg1;
- (void)presentKeepUsingUIForAppleID:(id)arg1 completion:(id)arg2;
- (void)dismissBasicLoginUIWithCompletion:(id)arg1;
- (void)presentLoginAlertWithError:(id)arg1 title:(id)arg2 message:(id)arg3 completion:(id)arg4;
- (void)presentBasicLoginUIWithCompletion:(id)arg1;
- (id)initWithContext:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) NSUInteger hash;
@property(readonly) Class superclass;

@end

