#import <Foundation/Foundation.h>
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NSButton, NSString, NSTextField;

@interface AKKeepUsingController : NSViewController
{
    NSString *_existingAccount;
    NSTextField *_header;
    NSButton *_useExistingAccountButton;
    id _useExistingAction;
    id _useOtherAction;
}


@property(copy) id useOtherAction; // @synthesize useOtherAction=_useOtherAction;
@property(copy) id useExistingAction; // @synthesize useExistingAction=_useExistingAction;
@property NSButton *useExistingAccountButton; // @synthesize useExistingAccountButton=_useExistingAccountButton;
@property NSTextField *header; // @synthesize header=_header;
@property(retain) NSString *existingAccount; // @synthesize existingAccount=_existingAccount;
- (void)useOtherAccountButtonPressed:(id)arg1;
- (void)keepUsingExistingAccountbuttonPressed:(id)arg1;
- (void)awakeFromNib;
- (id)init;

@end

