//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface ADMNetworkTimeServer : NSObject
{
    NSString *_descriptiveName;
    NSString *_address;
}

+ (instancetype)serverWithConfigurationString:(NSString*)arg1;
- (NSString*)configurationString;
- (NSString*)address;
- (NSString*)descriptiveName;
- (void)setAddress:(NSString*)arg1;
- (NSString*)description;
- (void)setDescriptiveName:(NSString*)arg1;
- (instancetype)initWithConfigurationString:(NSString*)arg1;

@end

