//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>
#import <Foundation/NSArray.h>

@class ADMNetworkTimeServer;

@interface ADMNetworkTimeClient : NSObject
{
}

+ (instancetype)sharedNetworkTimeClient;
- (void)setServer:(ADMNetworkTimeServer*)arg1;
- (ADMNetworkTimeServer*)server;
- (NSArray<ADMNetworkTimeServer*>*)servers;
- (void)setServers:(NSArray<ADMNetworkTimeServer*>*)arg1;
- (void)stopWithAuthorization:(struct AuthorizationOpaqueRef *)arg1;
- (void)startWithAuthorization:(struct AuthorizationOpaqueRef *)arg1;
- (BOOL)isRunning;

@end

