//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface CBColorSample : NSObject
{
    double _lux;
    double _CCT;
    unsigned long long _mode;
    unsigned long long _type;
    id _xy;
    id _XYZ;
}

@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(nonatomic) unsigned long long mode; // @synthesize mode=_mode;
@property(readonly, nonatomic) double CCT; // @synthesize CCT=_CCT;
@property(readonly, nonatomic) id XYZ; // @synthesize XYZ=_XYZ;
@property(readonly, nonatomic) id xy; // @synthesize xy=_xy;
@property(readonly, nonatomic) double lux; // @synthesize lux=_lux;
- (id)description;
- (id)copyDataInDictionary;
@property(readonly, nonatomic) long long colorBin;
- (double)LuxDifferenceWith:(id)arg1;
- (double)CCTDifferenceWith:(id)arg1;
- (double)colorDeltaEWith:(id)arg1;
@property(readonly, nonatomic) id Lab;
- (void)fillInTristimulus;
- (void)fillInChromaticity;
- (void)setXYZ:(id)arg1;
- (void)setXy:(id)arg1;
- (id)initWithHIDEvent:(struct __IOHIDEvent *)arg1;
- (id)initWithChromaticity:(id)arg1 illuminance:(double)arg2 andTempterature:(double)arg3;
- (id)initWithTristimulus:(id)arg1 illuminance:(double)arg2 andTempterature:(double)arg3;
- (id)init;

@end

