#import <Foundation/Foundation.h>
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol NSXPCListenerDelegate;

@class NSString, NSXPCInterface, NSXPCListener;

@interface AKAdaptiveService : NSObject <NSXPCListenerDelegate>
{
    NSXPCInterface *_exportedInterface;
    id _exportedObject;
    NSXPCListener *_listener;
    id _interruptionHandler;
    id _invalidationHandler;
}


@property(copy) id invalidationHandler; // @synthesize invalidationHandler=_invalidationHandler;
@property(copy) id interruptionHandler; // @synthesize interruptionHandler=_interruptionHandler;
- (BOOL)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (id)listenerEndpoint;
- (void)resume;
- (void)dealloc;
- (id)initWithInterface:(id)arg1 weakObject:(id)arg2;
- (id)initWithInterface:(id)arg1 strongObject:(id)arg2;
- (id)_initWithInterface:(id)arg1 object:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) NSUInteger hash;
@property(readonly) Class superclass;

@end

