#import <Foundation/Foundation.h>
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol AKAlertHandlerUIProvider;

@interface AKAlertHandler : NSObject
{
     id  _uiProvider;
}

+ (id)sharedInstance;

@property __weak  id  uiProvider; // @synthesize uiProvider=_uiProvider;
- (id)_URLWithString:(id)arg1 byAppendingParameters:(id)arg2;
- (void)_openUpgradeAccountSecurityLevelWithBundleID:(id)arg1;
- (void)_openPasscodeSetup;
- (void)_openSpyglass;
- (id)notificationDictionaryWithTitle:(id)arg1 message:(id)arg2 defaultButton:(id)arg3 alternateButton:(id)arg4;
- (BOOL)showAlert:(id)arg1 primaryAction:(id)arg2 altAction:(id)arg3 cancelAction:(id)arg4;
- (BOOL)showAlert:(id)arg1 primaryAction:(id)arg2 altAction:(id)arg3;
- (void)_showAlertForPasscodeSetupWithCompletion:(id)arg1;
- (void)_showAlertForUnderageAccount:(id)arg1 withCompletion:(id)arg2;
- (void)_showAlertForCannotFindServerWithCompletion:(id)arg1;
- (void)_showAlertForInsufficientSecurityLevelWithBundleID:(id)arg1 completionHandler:(id)arg2;
- (void)_showAlertForUnverifiedEmailWithCompletion:(id)arg1;
- (void)_showAlertForAccountNotSupportedWithCompletion:(id)arg1;
- (void)_showAlertForMissingAppleAccountWithCompletion:(id)arg1;
- (void)_showAlertForInvalidContextWithCompletion:(id)arg1;
- (void)showAlertForError:(id)arg1 withAuthKitAccount:(id)arg2 withCompletion:(id)arg3;
- (void)showAlertForError:(id)arg1 withCompletion:(id)arg2;

@end

