#import <Foundation/Foundation.h>
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>



@protocol AKAppleIDAuthenticationUIProvider;

@protocol AKAppleIDAuthenticationDelegate <NSObject>

@optional
- (void)authenticationController:(AKAppleIDAuthenticationController *)arg1 shouldContinueWithAuthenticationResults:(NSMutableDictionary *)arg2 error:(NSError *)arg3 forContext:(AKAppleIDAuthenticationContext *)arg4 completion:(void (^)(_Bool))arg5;
- (_Bool)authenticationController:(AKAppleIDAuthenticationController *)arg1 shouldContinueWithAuthenticationResults:(NSMutableDictionary *)arg2 error:(NSError *)arg3 forContext:(AKAppleIDAuthenticationContext *)arg4;
@end

NS_ASSUME_NONNULL_BEGIN

@class AKAppleIDAuthenticationContextManager, AKAccountRecoveryContext, NSLock, NSString, NSXPCConnection, NSXPCListenerEndpoint;


@interface AKAppleIDAuthenticationController : NSObject
{
    NSString *_serviceID;
    NSXPCListenerEndpoint *_daemonXPCEndpoint;
    NSXPCConnection *_authenticationServiceConnection;
    AKAppleIDAuthenticationContextManager *_contextManager;
    NSLock *_connectionLock;
    id _deallocHandler;
}

+ (id)sensitiveAuthenticationKeys;

@property(copy, nonatomic) id deallocHandler; // @synthesize deallocHandler=_deallocHandler;
- (NSXPCConnection*)_authenticationServiceConnection;
- (void)forceURLBagUpdateForAltDSID:(id)arg1 urlSwitchData:(id)arg2 completion:(id)arg3;
- (id)_urlBagFromCache:(BOOL)arg1 altDSID:(id)arg2 withError:(id *)arg3;
- (void)fetchURLBagForAltDSID:(id)arg1 completion:(id)arg2;
- (id)accountNamesForAltDSID:(id)arg1;
- (void)validateVettingToken:(id)arg1 forAltDSID:(id)arg2 completion:(id)arg3;
- (void)persistMasterKeyVerifier:(id)arg1 context:(id)arg2 completion:(id)arg3;
- (void)verifyMasterKey:(id)arg1 context:(id)arg2 completion:(id)arg3;
- (void)renewRecoveryTokenWithContext:(id)arg1 completion:(id)arg2;
- (void)teardownFollowUpWithContext:(id)arg1 completion:(id)arg2;
- (void)synchronizeFollowUpItemsForContext:(id)arg1 completion:(id)arg2;
- (BOOL)synchronizeFollowUpItemsForContext:(id)arg1 error:(id *)arg2;
- (void)getServerUILoadDelegateWithContext:(id)arg1 completion:(id)arg2;
- (void)getServerUILoadDelegateForAltDSID:(id)arg1 completion:(id)arg2;
- (id)activeLoginCode:(id *)arg1;
- (BOOL)isDevicePasscodeProtected:(id *)arg1;
- (void)updateStateWithExternalAuthenticationResponse:(id)arg1 forAppleID:(id)arg2 completion:(id)arg3;
- (void)updateStateWithExternalAuthenticationResponse:(id)arg1 forContext:(id)arg2 completion:(id)arg3;
- (void)reportSignOutForAllAppleIDsWithCompletion:(id)arg1;
- (void)reportSignOutForAppleID:(id)arg1 service:(long long)arg2 completion:(id)arg3;
- (void)checkInWithAuthenticationServerForAppleID:(id)arg1 completion:(id)arg2;
- (void)performCircleRequestWithContext:(id)arg1 completion:(id)arg2;
- (void)validateLoginCode:(unsigned long long)arg1 forAppleID:(id)arg2 completion:(id)arg3;
- (void)generateLoginCodeWithCompletion:(id)arg1;
- (void)checkSecurityUpgradeEligibilityForContext:(id)arg1 completion:(id)arg2;
- (void)configurationInfoWithIdentifiers:(id)arg1 forAltDSID:(id)arg2 completion:(id)arg3;
- (void)setConfigurationInfo:(id)arg1 forIdentifier:(id)arg2 forAltDSID:(id)arg3 completion:(id)arg4;
- (void)warmUpVerificationSessionWithCompletion:(id)arg1;
- (BOOL)revokeAuthorizationForApplicationWithClientID:(id)arg1 error:(id *)arg2;
- (BOOL)deleteAuthorizationDatabase:(id *)arg1;
- (id)fetchAuthorizedAppListWithContext:(id)arg1 error:(id *)arg2;
- (id)fetchDeviceListWithContext:(id)arg1 error:(id *)arg2;
- (void)fetchDeviceMapWithContext:(id)arg1 completion:(id)arg2;
- (void)fetchDeviceListWithContext:(id)arg1 completion:(id)arg2;
- (void)fetchAuthModeWithContext:(id)arg1 completion:(id)arg2;
- (void)updateUserInformationForAltDSID:(id)arg1 userInformation:(id)arg2 completion:(id)arg3;
- (void)getUserInformationForAltDSID:(id)arg1 completion:(id)arg2;
- (void)fetchUserInformationForAltDSID:(id)arg1 completion:(id)arg2;
- (void)setAppleIDWithDSID:(id)arg1 inUse:(BOOL)arg2 forService:(long long)arg3;
- (void)setAppleIDWithAltDSID:(id)arg1 inUse:(BOOL)arg2 forService:(long long)arg3;


NS_ASSUME_NONNULL_END


- (void)authenticateWithContext:(id)arg1 completion:(void (^)(NSDictionary*, NSError*))arg2;
@property __weak  id  delegate;
- (void)dealloc;
- (id)initWithIdentifier:(id)arg1 daemonXPCEndpoint:(id)arg2;
- (id)initWithDaemonXPCEndpoint:(id)arg1;
- (id)initWithIdentifier:(id)arg1;
- (id)init;
-(void)setUiProvider:(id <AKAppleIDAuthenticationUIProvider>)provider;

@end
