#import <Foundation/Foundation.h>
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AKAuthorizationClientProtocol-Protocol.h"

@protocol AKAuthorizationUIProvider;

@interface AKAuthorizationClientImpl : NSObject <AKAuthorizationClientProtocol>
{
     id  _uiProvider;
}


@property(retain)  id  uiProvider; // @synthesize uiProvider=_uiProvider;
- (void)presentAuthorizationUIForContext:(id)arg1 completion:(id)arg2;

@end

